### ISSUE TITLE
Can zipped resources be supported?

### ISSUE THREAD

**Issue by peterdesmet** [timrobertson100/frictionless-transforms#1]
I'm trying to read a `datapackage.json` where one of the sources is zipped (which is supported by data package), but got an error that `zip` is not supported (not sure by which package). @niconoe would it be possible to support this?

```
Opening the source data package...
No preprocessing module found, skipping
Load into SQLite...
Traceback (most recent call last):
  File "/Users/peter_desmet/anaconda3/envs/inbo/bin/ft", line 11, in <module>
    load_entry_point('frictionless-transforms', 'console_scripts', 'ft')()
  File "/Users/peter_desmet/anaconda3/envs/inbo/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/peter_desmet/anaconda3/envs/inbo/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/peter_desmet/anaconda3/envs/inbo/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/peter_desmet/anaconda3/envs/inbo/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/peter_desmet/Coding/Repositories/tdwg/frictionless-transforms/ft.py", line 32, in cli
    engine = package_to_sqlite(input_package)
  File "/Users/peter_desmet/Coding/Repositories/tdwg/frictionless-transforms/helpers.py", line 49, in package_to_sqlite
    package.save(storage='sql', engine=engine)
  File "/Users/peter_desmet/anaconda3/envs/inbo/lib/python3.7/site-packages/datapackage/package.py", line 458, in save
    storage.write(bucket, source())
  File "/Users/peter_desmet/anaconda3/envs/inbo/lib/python3.7/site-packages/tableschema_sql/storage.py", line 237, in write
    collections.deque(gen, maxlen=0)
  File "/Users/peter_desmet/anaconda3/envs/inbo/lib/python3.7/site-packages/tableschema_sql/writer.py", line 38, in write
    for row in rows:
  File "/Users/peter_desmet/anaconda3/envs/inbo/lib/python3.7/site-packages/tableschema/table.py", line 211, in iter
    with self.__stream as stream:
  File "/Users/peter_desmet/anaconda3/envs/inbo/lib/python3.7/site-packages/tabulator/stream.py", line 288, in __enter__
    self.open()
  File "/Users/peter_desmet/anaconda3/envs/inbo/lib/python3.7/site-packages/tabulator/stream.py", line 409, in open
    raise exceptions.FormatError(message)
tabulator.exceptions.FormatError: Format "zip" is not supported
```

**Comment by timrobertson100** [comment]
I can't see anything in [the Resource spec](https://specs.frictionlessdata.io/data-resource/#language) indicating that a compressed file should be supported, so I would assume not; there would have to be some metadata indicating what compression was being used as that can't be guessed.

You can zip up an entire DP though with locally addressed data files (i.e. similar to a DwC-A).

Edited to add: I see the Java DP implementation only supports CSV and JSON (even though the spec refers to xls)

**Comment by timrobertson100** [comment]
I presume the question relates to [this line](https://github.com/tdwg/dwc-for-biologging/blob/4fe7a1b93afefb38b3d59704ed0c35cec909d9bb/use-cases/movebank-inbo/datapackage.json#L189)

I was able to read `reference-data` and `gps` in Java by replacing those with locally referenced CSVs (well, I only used one file) and changing the `timestamp` to a String type, which ended up [like this](https://gist.github.com/timrobertson100/c63182fd3a91a45e8404bfe38d00c679).

**Comment by peterdesmet** [comment]
The datetime issue is resolved in the latest version on dwc-for-biologging.

Zips are definitely supported in the specs: https://specs.frictionlessdata.io/patterns/#compression-of-resources (there's a typo in the example in the docs that I have corrected in a PR), but not yet supported in all libraries depending on it: https://github.com/frictionlessdata/frictionless-py/issues/444

**Comment by timrobertson100** [comment]
Good to know. Thanks @peterdesmet 
The Java libs don't seem to support it but I assume that can be fixed fairly easily.

**Comment by peterdesmet** [comment]
@niconoe implementation worked out of the box for me. Like you, I adapted it to a package with single reference-data + gps file, and that worked too. So far so good for Python and Java.

**Comment by niconoe** [comment]
I'll investigate zip support, that's indeed in the spec, so should be supported!

FYI @timrobertson100 (general impression, already discussed with @peterdesmet): the datapackage ecosystem (datapackage-py, frictionless-py, tabulator, tableschema-sql-py, ...) appears to be a little more messy / less documented / less complete than what I expected, hence some surprises like this about what's supported/implemented and what's not. 

Nothing insurmountable, but I suspect for some features, we'll have to choose between implementing a "local quick and dirty fix" to our tool, or to do a longer term contribution to improve the core libraries themselves. I obviously prefer the latter, long-term approach, but it's not always the quickest way to get something running :)
